import { existsSync, readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import nextConfig from "../next.config";

describe("push service worker", () => {
  it("is independent of Next.js build assets", () => {
    const worker = readFileSync("public/sw.js", "utf8");

    expect(worker).not.toContain("__SW_MANIFEST");
    expect(worker).not.toMatch(/\/_next\/static\/[^"']+\.(?:js|css)/);
    expect(worker).toContain('"/_next/static/"');
    expect(worker).toContain('addEventListener("push"');
    expect(worker).toContain('addEventListener("notificationclick"');
  });

  it("ships a standalone branded offline document", () => {
    expect(existsSync("public/offline.html")).toBe(true);
    if (!existsSync("public/offline.html")) return;

    const offline = readFileSync("public/offline.html", "utf8");
    expect(offline).toContain("Jste offline");
    expect(offline).toContain("/habitat-logo.webp");
    expect(offline).not.toContain("/_next/");
  });

  it("is not regenerated by the Next.js build", () => {
    expect(nextConfig).not.toHaveProperty("webpack");
  });
});
