import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import nextConfig from "../next.config";

describe("push service worker", () => {
  it("is independent of Next.js build assets", () => {
    const worker = readFileSync("public/sw.js", "utf8");

    expect(worker).not.toContain("__SW_MANIFEST");
    expect(worker).not.toContain("/_next/");
    expect(worker).toContain('addEventListener("push"');
    expect(worker).toContain('addEventListener("notificationclick"');
  });

  it("is not regenerated by the Next.js build", () => {
    expect(nextConfig).not.toHaveProperty("webpack");
  });
});
